sales_admin/megaphone/config/routes.rb
Rails.application.routes.draw do
  root to: 'invoices#index'

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :invoices, only: [:index, :import, :delete] do
    get 'index', on: :collection
    post 'import', on: :collection
    delete 'destroy', on: :collection
  end
end

sales_admin/megaphone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

sales_admin/megaphone/app/models/invoice.rb
require 'csv'

class Invoice < ApplicationRecord
  def self.import(file)
    invoice_array = [].tap do |arr|
      CSV.foreach(file.path,
                headers: true,
                header_converters: ->(name) { name.downcase.sub(' ', '_') }) do |invoice|
        invoice['item_price'] = invoice['item_price'].to_f * 100
        arr.push invoice.to_h
      end
    end
    Invoice.insert_all! invoice_array
  end

  def item_price
    self[:item_price].to_f / 100.0
  end

  def total
    item_price * quantity
  end
end

sales_admin/megaphone/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

sales_admin/megaphone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

sales_admin/megaphone/app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def index
    @invoices = Invoice.all
    @sum = @invoices.reduce(0) { |sum, invoice| sum + invoice.total }
  end

  def import
    Invoice.import(params[:file])
    redirect_to root_url
  rescue StandardError => e
    Rails.logger.error e
    redirect_to root_url, notice: 'There was an issue loading your CSV'
  end

  def destroy
    Invoice.destroy_all
    redirect_to root_url
  end
end

sales_admin/megaphone/app/helpers/application_helper.rb
module ApplicationHelper
end

sales_admin/megaphone/app/helpers/home_helper.rb
module HomeHelper
end

sales_admin/megaphone/app/helpers/invoices_helper.rb
module InvoicesHelper
end

sales_admin/megaphone/app/views/invoices/import.html.erb
<h1>Invoices#import</h1>
<p>Find me in app/views/invoices/import.html.erb</p>

sales_admin/megaphone/app/views/invoices/index.html.erb
<%= form_tag import_invoices_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import CSV" %>
<% end %>
<h2>
  Total Revenue: <%= number_to_currency @sum %>
</h2>
<%= button_to "CLEAR", { controller: :invoices, action: 'destroy' }, method: :delete %>
<table>
  <thead>
    <tr>
      <th>Customer Name</th>
      <th>Item Description</th>
      <th>Item Price</th>
      <th>Quantity</th>
      <th>Merchant Name</th>
      <th>Merchant Address</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.customer_name %></td>
        <td><%= invoice.item_description %></td>
        <td><%= number_to_currency invoice.item_price %></td>
        <td><%= invoice.quantity %></td>
        <td><%= invoice.merchant_name %></td>
        <td><%= invoice.merchant_address %></td>
        <td><%= number_to_currency invoice.total %></td>
      </tr>
    <% end %>
  </tbody>
</table>

sales_admin/megaphone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Megaphone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>
    <%= yield %>
  </body>
</html>